### ISSUE TITLE
[tracking] Steps toward the Solo5 0.3.0 release

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#217]
**Overall goals**

1. Our primary goal is to surface the new features developed since the last formal release done together with MirageOS 3.0. In no particular order, these are:
    
    * The ukvm monitor ported to run on FreeBSD.
    * The Solo5 kernel`^W`base ported to run on ARM64, and the ukvm monitor ported to run Linux/KVM on ARM64.
    * Support for Muen SK as a monitor.
    * Support for IncludeOS unikernels as guests.

2. A secondary but no less important goal is to improve the communication around _"what is Solo5?"_ for this release: 
    
    * As a minimum, we need to refactor our documentation to clearly point "end users" (i.e. MirageOS and IncludeOS unikernel developers, Muen SK developers) to instructions on how to build Solo5 guests for their respective platforms.

    * We should also consider #172 (renaming ukvm to a more generic name); the reference to KVM in the name is confusing and no longer reflects the scope of the monitor. However, this will require a bunch of churn in downstream projects (mainly MirageOS) since these are using `ukvm` as a target name.

3. Thirdly, we should consider architecture and API changes going forward, and as a minimum either revive or drop/defer #200 (Minimal refresh of Solo5 APIs). 

**Rough list of tasks to complete**

This is an amalgamation of the Solo5 tasks and downstream (currently mainly MirageOS) tasks following from these goals, with dependent issues where these exist. I've sorted these by rough priority.

_Must have:_ (i.e. if it's not done it ain't in the release)

* [x] Complete Muen SK support on the MirageOS side (#194).
* [x] Complete IncludeOS support (#212).
* [x] Complete porting MirageOS downstream packages to ARM64 where required.
* [x] "End user" documentation refactoring + document those features which make it into the release.

_Nice to have:_

* [x] Minimal refresh of Solo5 APIs (#200)
* [x] ARM64 CI for MirageOS. As a minimum, the equivalent of "what Travis does for mirage/mirage-skeleton today" could be implemented fairly straightforwardly with eg. a surf-build setup.
* ~~IncludeOS's liveupdate support via `solo5_exec` (https://github.com/Solo5/solo5/pull/219)~~

_Optional:_

* ~~Rename ukvm to a more generic name (#172)~~ (deferred until after this release)

Tagging various folks responsible for the features we want to surface:

@djwillia @ricarkol @hannesm @Kensan @Weichen81 

Other interested parties and downstreams:

@perbu @amirmc @avsm @yomimono

Feel free to unsubscribe if you don't want the noise.

**Comment by hannesm** [comment]
I'd like #172 to be handled within this release (and happy to work on the mirage tool&lib for renaming).  I'd also be happy if #200 gets merged before a release (together with upstream changes in mirage-*-solo5).

**Comment by mato** [comment]
Updated some checkboxes. Struck out the `solo5_exec` change, as the consensus in Marrakesh was that we won't do that (/cc @ricarkol). I'll do a more complete update on this issue in due course.

**Comment by mato** [comment]
I just tagged `v0.3.0`, so closing this. Now to gradually publish the OPAM packages for MirageOS.
