### ISSUE TITLE
[tracking] Upstream Mirage/Solo5

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#36]
This issue tracks the individual tasks required to upstream (or otherwise release) Mirage/Solo5, referring to dependent issues or PRs as appropriate:

Must have:
- [x] Remove dependencies on Mini-OS (#19, #24, djwillia/mirage-platform#2, djwillia/mirage#1).
- [x] Non-busy-looping scheduler (#33, djwillia/mirage-platform#5, djwillia/mirage-net-solo5#1).
- [x] Pass a command line to the unikernel. (#20, #41, djwillia/mirage-platform#6).
- [x] Rename `qemu` target to `virtio` in Mirage tool (djwillia/mirage#2).
- [x] Implement `mirage-bootvar-solo5` to parse bootvars from command line (djwillia/mirage-bootvar-solo5#1).
- [x] Freestanding builds of `zarith` and `gmp`. Currently required for plain HTTP due to mirage/mirage#543. (done in djwillia/opam-solo5)
- [x] Stable enough to pass sustained load tests (e.g. `siege` of HTTP and HTTPS unikernel). Issues found so far: #58, #60. Status: OK, provided the the GC is tuned appropriately.
- [x] Decide on git repository layout, ownership and process of upstreaming. See "preparation for and upstreaming of Mirage/Solo5" comment below.
- [x] Upstreamed!

Nice to have:
- [x] TLS stack working. Requires a Solo5 "port" of `mirage-entropy` and adapting the `nocrypto` build system to use it, plus sorting out the resulting OPAM dependencies (djwillia/mirage#3, djwillia/opam-solo5#4).
- Standalone test programs for Solo5 APIs (#37).

Out of scope / future release:
- Support for >1 network or block device.

**Comment by mato** [comment]
### Preparation for and upstreaming of Mirage/Solo5

1. Decide on repository naming and ownership. We have a bunch of repos that are Solo5 specific. Should we move them into a `solo5/` org or into `mirage/`. Decision: move into `mirage/` since they are parallels to the existing `xen` and `unix` variant repositories that are already there.

  Overall picture of repository/opam/org relationships:

  ````
OPAM package            Git repository (current)          Git repository (upstream)

mirage                  djwillia/mirage#solo5             mirage/mirage (upstream via pr)
mirage-solo5            djwillia/mirage-platform#solo5    
                            >> djwillia/mirage-solo5          mirage/mirage-solo5
mirage-block-solo5      djwillia/mirage-block-solo5       mirage/mirage-block-solo5
mirage-net-solo5        djwillia/mirage-net-solo5         mirage/mirage-net-solo5
mirage-bootvar-solo5    djwillia/mirage-bootvar-solo5     mirage/mirage-bootvar-solo5
mirage-console          djwillia/mirage-console#solo5
>> mirage-console-solo5 >> djwillia/mirage-console-solo5  mirage/mirage-console-solo5
mirage-entropy-solo5    mato/mirage-entropy#solo5         TBD, need to discuss with @hannesm
nocrypto                mato/ocaml-nocrypto#solo5         TBD, need to discuss with @hannesm
ocaml-freestanding      mato/ocaml-freestanding           mirage/ocaml-freestanding
solo5-kernel-ukvm       djwillia/solo5                    leave as is
solo5-kernel-virtio     djwillia/solo5                    leave as is
gmp-freestanding        - (opam only)                     -
zarith-freestanding     - (opam only)                     -
-                       djwillia/opam-solo5               leave as is

(>> means needs to be renamed)
````

2. Clean up package and repository relationships based on above:
  - [ ] Extricate `mirage-solo5` from `mirage-platform` fork.
  - [x] Extricate `mirage-console-solo5` from `mirage-console` fork.
  - [x] Email Github support to convert forks to normal repositories.
  - [ ] Once Github "unforks" the requested repositories, transfer them to Mirage org on Github.

4. Publish the `mirage-solo5*` packages to `opam.ocaml.org`.
  - [ ] Clean up `opam` files for these packages (correct maintainer, repo URLs, ...)
  - [ ] Cut releases of each package that will be published.
  - [ ] @mato to Figure out with @hannesm what to do about `mirage-entropy-solo5` and `nocrypto` to avoid any code duplication here.

5. Mirage frontend changes.
  - [ ] Submit PR for merging Mirage frontend changes from `djwillia/mirage#solo5`
into `mirage/mirage`.

**Comment by avsm** [comment]
See mirage/mirage-console#41 for the split of the mirage-console packages into separate OPAM packages.  That will stay in one repo for now but can easily be split up later once things settle -- the important thing is that there is now one OPAM package per ocamlfind package installed by the console variants.

**Comment by hannesm** [comment]
Entropy support: I started off with @mato branch for entropy and massaged it a bit to avoid code duplcation.  See the branch over [here](https://github.com/hannesm/mirage-entropy/tree/solo5).  The remaining piece of work is to, instead of having depopts and a single package, revert this change, and use no depopts, but two packages (`mirage-entropy-xen` and `mirage-entropy-solo5`).  The C stub is a symbolic link, thus no code duplication there.  I moved most of the OCaml code (apart from `connect`, which requires the `OS` module from `mirage-xen`/`mirage-solo5`) into the common `Entropy` module.  I've no clue how to embed the call to `postconf` in a system using topkg (but likely the [build documentation](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALbuild) will help (the `?pre` looks promising)).

nocrypto: same story, see branch [here](https://github.com/hannesm/ocaml-nocrypto/tree/solo5).  after separating the entropy packages into two, the opam file will need some attention.  There is code duplication (nocrypto_entropy_solo5 and nocrypto_entropy_xen are nearly the same, apart from the `module E = Entropy_XXX` line).  Should investigate further how to share the OCaml code.  As preparations, I added two PRs to nocrypto with cleanups.

In order to get the dependencies adjusted, I added a [mirage-no-solo5](https://github.com/ocaml/opam-repository/pull/7002) package (similar to mirage-no-xen).  The purpose is to be able to express 'either there is solo5 support in nocrypto, then we also need a freestanding gmp and zarith, or there is no solo5 support in nocrypto'.

**Comment by hannesm** [comment]
entropy: 
 - [moved to topkg](https://github.com/mirage/mirage-entropy/pull/28)
 - [preparing solo5](https://github.com/mirage/mirage-entropy/pull/29)
 - [supporting solo5](https://github.com/hannesm/mirage-entropy/commit/a011b9e2ce36c3d944a9fe143f09c09a81ab3c24) (does not build yet, sorry)

nocrypto:
 - [rename (number 2 above)](https://github.com/mirleft/ocaml-nocrypto/pull/99)
 - also minor changes were merged: [no dep on stdio](https://github.com/mirleft/ocaml-nocrypto/commit/a45ea6aaab2f22c657abe553ed6b045ea78e6fae), [rename](https://github.com/mirleft/ocaml-nocrypto/commit/59b78cd0a167edd2523aae4a313c75bab0c3e0b9)

once I get the solo5 branch in mirage-entropy-xen to work, the upcoming changes to nocrypto will only be the addition of the compilation of the C stubs (plus maybe some copy of the xen subfolder)!

**Comment by hannesm** [comment]
updates:
entropy [compiles now (and works for xen)](https://github.com/mirage/mirage-entropy/pull/30)
nocrypto [adjusted](https://github.com/hannesm/ocaml-nocrypto/tree/solo5)

I opened a PR to opam-solo5 https://github.com/Solo5/opam-solo5/pull/6 (while figuring out that I need some minor adjustments to the mirage tool for renaming).

as far as I'm concerned, this is a pretty clean and good solution to our demands.

**Comment by mato** [comment]
PRs to opam-repository submitted:
- ocaml/opam-repository#6983 (mirage-block-solo5)
- ocaml/opam-repository#7019 (solo5-kernel-ukvm)
- ocaml/opam-repository#7020 (solo5-kernel-virtio)
- ocaml/opam-repository#7021 (ocaml-freestanding)
- ocaml/opam-repository#7024 (gmp-freestanding)
- ocaml/opam-repository#7025 (mirage-solo5)
- ocaml/opam-repository#7029 (mirage-bootvar-solo5)
- ocaml/opam-repository#7030 (mirage-console-solo5)
- ocaml/opam-repository#7031 (mirage-net-solo5)
- ocaml/opam-repository#7032 (zarith-freestanding)

**Comment by hannesm** [comment]
https://github.com/mirage/mirage/pull/565 mirage changes (massaged into a single commit)

**Comment by mato** [comment]
This is now complete, closing.
