### ISSUE TITLE
[tracking] solo5 (virtio) on FreeBSD bhyve

### ISSUE THREAD

**Issue by hannesm** [Solo5/solo5#61]
status is: it works, but still needs some manual patches.  this uses clang instead of gcc.  the instructions are documented [here](https://hannes.nqsb.io/Posts/Solo5).  I haven't tested more than console yet.

Updates:
- [x] solo5 [PR build system fix](https://github.com/Solo5/solo5/pull/68)
- [x] solo5 [use `-nostdlibinc` and a `/tmp/include`](https://github.com/hannesm/solo5/commit/31c634280a884aee117e626635ebcc95d20aa2ae)
- [x] solo5: `cp` instructions at https://hannes.nqsb.io/Posts/Solo5
- [x] ocaml-freestanding [PR new openlibm](https://github.com/mirage/ocaml-freestanding/pull/4)
- [x] ocaml-freestanding [PR opam fix](https://github.com/mirage/ocaml-freestanding/pull/5)
- [x] ocaml-freestanding FreeBSD Makefile for OCaml (solution: conditional in configure.sh) 
- [x] ocaml-freestanding remove `-Wno-maybe-uninitialized` from nolibc (solution: same as above) see [FreeBSD branch](https://github.com/hannesm/ocaml-freestanding/commits/FreeBSD)
- [x] ocaml-freestanding: `rm sys/cdefs.h`
- [x] mirage using the solo5 PR
- [x] `export LD=/usr/local/bin/ld`

--- old stuff below ---

This issue is to track progress of upstreaming this into the solo5 mainline.  The biggest issue are include files.

- [x] libgcc.a is not needed to get linked in (it seems to be required on arm only, see #50 and https://github.com/mirage/mirage/pull/544), PR #63
- [x] solo5 uses `nostdinc`, but then includes `${CC} -print-file-name=include` as system includes.  It then includes `stddef.h` from there, which drags in `sys/_types.h` on FreeBSD.  There are other headers needed, such as `osreldate.h` (by openlibm).  In order to build `mirage-entropy-solo5` I needed to get rid of the gcc includes to get the intrinsics shipped with clang.  I've no proper idea how to deal with this best: provide our own `stddef.h`?  remove `nostdinc`?  Input is welcome how to solve this (note: the vanilla minios-xen uses `nostdinc` and does not use any system include (thus builds fine with clang); mirage modified minios drags in `stdint.h` and I wasn't able to get it working on FreeBSD).  e.g. grub completely ships their own header files.
- [x] ocaml-freestanding: POSIX `cp` does not have a `-d` flag [commit](https://github.com/hannesm/ocaml-freestanding/commit/0df20a1c3a30b733d61a37e229a578027aee8126) (which is there to copy `sys/time.h` and its symlink `time.h`) -- see [posix time.h](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/time.h.html) vs [posix sys/time.h](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/time.h.html)
- [x] ocaml-freestanding: openlibm does use `gcc` as `CC` on non-Darwin systems, and needs to be patched (should be upstreamed to contain `CC?=cc` behaviour) (fixed upstream in openlibm, see https://github.com/mirage/ocaml-freestanding/pull/4)
- [x] ocaml-freestanding: other `Makefile.x86_64` for FreeBSD [commit (includes the openlibm fix)](https://github.com/hannesm/ocaml-freestanding/commit/2dc668829d18e6e01b6bedfc63a3230720acecb2)
- [x] ocaml-freestanding: nolibc uses `-Wall -Werror`, but excludes `-Wno-maybe-uninitialized` which is gcc only (clang fails on that unknown option) -- a compiler-specific Makefile rule may solve that (can we fix the code instead?)
- [x] mirage: need to use `ld` from ports (thus `/usr/local/bin/ld`), the system provided one is too old to cope with `-z max-page-size=0x1000` [commit](https://github.com/hannesm/mirage/commit/889a45a34a9520856a326bd829fcd904e0ae8206)

comments, especially on how to sanely deal with `stddef.h` and friends (`machine/_types.h machine/endian.h sys/_types.h sys/cdefs.h x86/_types.h x86/endian.h osreldate.h`) would be highly appreciated!

**Comment by mato** [comment]
Regarding include files, we can't remove `-nostdinc` as the results of including anything from `/usr/include` are unpredictable. I think the best option is to lift musl `stddef.h`, `stdint.h`, `stdarg.h` and the infrastructure needed to build their dependencies (`arch/x86_64/bits/alltypes.h.in`, `tools/mkalltypes.sed`, ...) and ship them with Solo5 directly. Musl supports clang so these should work fine (http://wiki.musl-libc.org/wiki/Supported_Platforms). Any objections to this approach? (ping @djwillia)

Regarding the ocaml-freestanding changes, there is a `configure.sh` which generates `Makeconf` at build time, so you could use this to detect if building on FreeBSD and/or clang and set the appropriate flags and asmrun Makefile there.

As for the dependency on `ld` from ports, not much we can do about that in the short term, other than:
1. Add `Makeconf` / `configure.sh`-style infrastructure to Solo5 and try and look for a good enough `ld` in "likely" places, failing if none was found.
2. Add pkg-config infrastructure to pass the correct `ld` from `solo5-kernel-virtio` through to `mirage`.

**Comment by djwillia** [comment]
@mato @hannesm I agree; it seems the best option is to put those headers into the tree.  

At the risk of sounding ignorant, if we are properly providing a build container (e.g., like mato's one from unikernel-runner), do we really need to solve compilation-on-multiple-platform issues?  I see the importance of having the resultant binaries and images run on other systems, but not the build?  The only possible upside I see is that building on multiple platforms may expose more bugs or weirdness that should be fixed regardless.  Am I missing something?  Has Docker not yet been made to work in a stable way with FreeBSD?

**Comment by hannesm** [comment]
@djwillia while https://github.com/djwillia/solo5/commit/5084a971b5502a20bbe048f9dc20b9d37d5577b6 is not severe, I think https://github.com/mato/ocaml-freestanding/commit/b0c34ec8e57a010ad9a5e18f7e68b8b7644f0632 is a nice example why supporting multiple build platforms is a good idea.  Detecting bugs, be compatible to some POSIX standard...

clearly you can depend on having some docker installation to build solo5.  I appreciate more minimalistic approaches (which do not include dependency on yet another PL runtime (Go) etc.) for building a piece of software, esp since getting solo5 to build on FreeBSD (or other POSIX systems) is not a big pain.  I'd not want to add a dependency onto `autoconf` and friends, but some conditionals based on `uname -s` during build is IMHO fine.  while I have not tried docker (did not have the demand for it), there is a port to FreeBSD AFAIK.

**Comment by mato** [comment]
@djwillia The Docker on FreeBSD port seems dormant (https://github.com/kvasdopil/docker/tree/freebsd-compat). In any case, while providing a dockerized build is great I don't think we should make Docker a hard dependency. And, as both you and @hannesm agree, building on multiple platforms tends to expose bugs so is worth the trouble :-)

**Comment by djwillia** [comment]
@hannesm @mato Thanks for the explanations; makes sense to me!

**Comment by mato** [comment]
@hannesm I've looked at ways of resolving the header file issue and unfortunately it's more complicated than I originally thought.

There are two groups of header files involved:

1. Standard C definitions: `stdint.h`, `stddef.h`, `stdarg.h`, ... `gcc` bundles these, `clang` does not.
2. CPU intrinsics: `cpuid.h`, `x86intrin.h`, ... `gcc` and `clang` both bundle these and they are relied on by (at least) the `nocrypto` code.

We can supply our own headers for "group 1", but not for "group 2" since these are compiler specific. However, I can't find any practical way of making it work:

1. With `gcc`, **both** groups are in the directory we get via `gcc -print-file-name=include`. So we can't get one without the other, hence shipping our own headers is kind of pointless.
2. With `clang` (on my FreeBSD 10.3-RELEASE test VM, clang 3.4.1) the "group 2" files live in `/usr/include/clang/3.4.1`. According to the man page, `clang` has a `-nostdlibinc` option which is documented as:

 > Do not search the standard system directories for include files, but do search compiler builtin include directories.

 However, this does not actually work -- I tried it with a test program and the compiler cannot find `cpuid.h` with `-nostdlibinc`. I tried various other options to `clang` but could not find one that would point me to the "builtin" include directory.

Conclusion: In the interests of getting initial versions of the Mirage/Solo5 packages published, I'd like to postpone this work, keep the dependency on the `libgcc` headers and revisit the `clang` situation later.

**Comment by hannesm** [comment]
thanks for investigating. regarding 2: `clang -print-file-name=include` returns the directory for group 2 (on my FreeBSD-CURRENT `/usr/bin/../lib/clang/3.8.0/include`, there is no longer any `/usr/include/clang`)

**Comment by mato** [comment]
Ok, so that's changed. On 10.3-RELEASE it returns `/usr/lib/include`. Can you check if the following compiles with `-nostdlibinc` on CURRENT?
````
#include <cpuid.h>

int main(int argc, char *argv[])
{
    int max = __get_cpuid_max (0, &max);
    return max;
}
````

**Comment by hannesm** [comment]
that works fine here (clang 3.8.0):
```
] cc -nostdlibinc -o foo foo.c
foo.c:5:35: warning: passing 'int *' to parameter of type 'unsigned int *' converts between pointers to
      integer types with different sign [-Wpointer-sign]
    int max = __get_cpuid_max (0, &max);
                                  ^~~~
/usr/bin/../lib/clang/3.8.0/include/cpuid.h:181:74: note: passing argument to parameter '__sig' here
static __inline int __get_cpuid_max (unsigned int __level, unsigned int *__sig)
                                                                         ^
1 warning generated.
] ./foo
] echo $?
20
```

**Comment by hannesm** [comment]
updates here:
- solo5: [https://github.com/Solo5/solo5/pull/68](build system fix) and [using `-nostdlibinc` and a `/tmp/include`](https://github.com/hannesm/solo5/commit/31c634280a884aee117e626635ebcc95d20aa2ae); `cp` instructions at https://hannes.nqsb.io/Posts/Solo5
- ocaml-freestanding: [new openlibm](https://github.com/mirage/ocaml-freestanding/pull/4),  [opam fix](https://github.com/mirage/ocaml-freestanding/pull/5), and minor hacks (https://github.com/hannesm/ocaml-freestanding/commits/FreeBSD): FreeBSD makefile for OCaml, remove Wno-maybe-uninitialized from nolibc
- mirage using the solo5 PR
- `export LD=/usr/local/bin/ld`

**Comment by hannesm** [comment]
I updated the task list at the top!

**Comment by mato** [comment]
@hannesm I got tired of having to hand-apply hacks to build and test virtio on FreeBSD, so I've integrated most of your changes:
- #102 has the Solo5 parts. Uses a variant of the `/tmp/myinclude` approach to make things work.
- mirage/ocaml-freestanding#9 has the rest.
Could you review/test these and let me know what you think? I've tested on `11.0-RELEASE` and partially on `10.3-RELEASE` and all seems fine.

The following parts are still missing for an "out of the box" experience:

- `conf-pkg-config` needs to gain a depext on `pkgconf` for FreeBSD.
- Makefile generation in `mirage` should be modified to set the default `LD` for Solo5 targets from the output of `pkg-config solo5-kernel-virtio --variable=ld`.

If you could handle the above I'd appreciate it!

**Comment by mato** [comment]
Additionally, the following two commits are required to build `gmp-freestanding` and `zarith-freestanding` on FreeBSD:
- https://github.com/hannesm/opam-repository/commit/ca31a93811d9bf61ce5432a76e627d93e8e19a92
- https://github.com/hannesm/opam-repository/commit/315c2d277f447da71ab77b639d6b730031766a92

**Comment by hannesm** [comment]
thx @mato -- the zarith-freestanding and gmp-freestanding have just been merged to opam-repository! :) (see https://github.com/ocaml/opam-repository/pull/7614)

**Comment by mato** [comment]
I've pushed some more fixes to both PRs. With these (and ocaml/opam-repository #7627) I can now build the whole stack (well, `static_website_tls`) and the built binary runs fine on `11.0-RELEASE`.

I've also been testing on `10.3-RELEASE`, things work 80% of the time there, unfortunately `mirage-entropy-solo5` will not build due to `clang -nostdlibinc` missing headers for the CPU builtins. I'm not going to try and fix this, suggest to ask people to just use `11.0-RELEASE` or newer.

@hannesm So, I think it's OK to merge #102 and mirage/ocaml-freestanding#9 -- if there are issues with `-CURRENT` (I hope not!) we can fix those separately.

**Comment by hannesm** [comment]
thanks (especially to @mato) we're finally in a state where this all works (more or less) out of the box, the only missing bit is the `LD` define, which is PR'ed in https://github.com/mirage/mirage/pull/623 and was just merged :)
