### ISSUE TITLE
[Tracking] Solo5 tasks for Mirage 3.0 release

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#82]
#Solo5 tasks under consideration for the Mirage 3.0 release, with (rough priority) and @mentions for those currently working on a task:
- [x] (1) _CI improvements and end to end testing_ (@mato).
  - `mirage/mirage-skeleton` Travis CI should build Solo5 targets. (done)
  - end to end testing and improved standalone tests: #112, #113, #114, #115, #120
  - Related issues: mirage/mirage#584.
- [x] (1) _Stabilise virtio drivers_ (@ricarkol). 
  - Iterative cleanups so that we always have something working.
  - Aim to move implementation to v1.0 of the spec.
  - Related issues: #78.
- [x] (1) _Audit ukvm interfaces_.
  - `ukvm` hypercall/device interfaces need assertions about invariants, eg. for out of range pointers or buffer sizes passed in by the guest.
  - Related issues: #99, #117
- [x] (1) _Audit ukvm ELF loader_.
  - There are multiple issues with the ukvm ELF loader. See #126.
- [x] (2) _Clean up interrupt and trap handlers_.
  - Switch to a single .S source for interrupt and trap handlers, use gas macros where needed rather than bash-script driven code generation.
  - Add internal interfaces and infrastructure to register/unregister interrupt handlers.
  - Improve debugging value of trap handlers (~~backtraces~~ and other info?).
  - Related issues: #32.
- [x] (2) _FreeBSD support_ (@mato, @hannesm).
  - Priority bumped by the need to test virtio on Byhve.
  - See #61, #102 for details.
- [x] (2) _`ukvm` host feature detection_. 
  - Friendly error message if `ukvm` doesn't support the host CPU or KVM interface.
  - Related issues: #9.
- ~~[ ] (3) _Improved memory protection_.~~
  - Guard pages, verify W^X is used as appropriate, unmapped zero page.
- [x] (4) _Integrated `mkimage` tool_.
  - #110

**Comment by mato** [comment]
@hannesm Should we consider supporting bhyve for Mirage 3.0? Depends on how much time you have from now until the (end-September) planned release.

**Comment by hannesm** [comment]
@mato appreciated.  still needs someone to do the tedious cleanups of include files... I'll focus on opam signing in september, and can't promise much time on bhyve

**Comment by mato** [comment]
The "clean up interrupt and trap handlers" item is now complete. I'm not going to deal with backtraces, stack unwinding on x86_64 without frame pointers is a very deep rabbit hole best left to a debugger.

**Comment by mato** [comment]
With the last batch of changes (#108, #109) virtio now appears stable, hurrah. I've ceremonially updated the checkmark.

**Comment by djwillia** [comment]
@mato we probably should uncheck "Audit ukvm interfaces" until we have something satisfying for https://github.com/Solo5/solo5/issues/117 so that it doesn't get forgotten

**Comment by mato** [comment]
@djwillia Ok, unchecked, checked the other two items now that we have automated tests and ukvm messages have been cleaned up

**Comment by amirmc** [comment]
Hi folks, I'm also tracking the priority 1 items from here over on https://github.com/mirage/mirage/issues/592.  Is `Audit ukvm interfaces` the only thing left to check off?

**Comment by mato** [comment]
@amirmc Yes, that's correct, and it depends on #117 which I hope to fix today or tomorrow.

**Comment by mato** [comment]
I've added a P1 item to audit the ukvm ELF loader, since while reviewing #123 I ran into several problems with it. See #126 for the issue.

**Comment by amirmc** [comment]
Since everything is ticked off, including the ELF loader fixes, can this now be closed? :)

**Comment by mato** [comment]
OPAM releases of the individual subcomponents still need to be tagged and CHANGELOGs written. I'm waiting for @yomimono to give me a go-ahead on this, presumably after the OPAM metadata changes in https://github.com/mirage/mirage-dev are ready for a "beta1" release of Mirage 3.

**Comment by mato** [comment]
Oh, and #146 needs merging which I'll do ASAP after I have some ACKs on it.

**Comment by mato** [comment]
Solo5 packages are now released and OPAM metadata is in [mirage/mirageos-3-beta](https://github.com/mirage/mirageos-3-beta) so I'm closing this as done.
